import EventPost from './EventPost'
import EventRecapPost, { recapPageCount } from './EventRecapPost'
import EventRecapClassic, { recapClassicPageCount } from './EventRecapClassic'
import SemesterCalendarPost from './SemesterCalendarPost'
import MemberSpotlightPost from './MemberSpotlightPost'
import AppsOpenPost from './AppsOpenPost'
import AppsOpenClassic from './AppsOpenClassic'
import EBoardPost from './EBoardPost'
import PhotoOverlayPost from './PhotoOverlayPost'

export const TEMPLATES = [
  {
    id: 'event',
    name: 'Event Announcement',
    category: 'Events',
    icon: '',
    component: EventPost,
    fields: [
      { key: 'photo', label: 'Background photo', type: 'image' },
      { key: 'eyebrow', label: 'Event type', placeholder: 'EMPLOYER EVENT', type: 'text' },
      { key: 'title', label: 'Event name', placeholder: 'Industry Night with Apollo MCE', type: 'text' },
      { key: 'date', label: 'Date', placeholder: 'Thu, Jan 30', type: 'text' },
      { key: 'time', label: 'Time', placeholder: '6:00 PM', type: 'text' },
      { key: 'location', label: 'Location', placeholder: 'Boyd GSRC', type: 'text' },
    ],
    defaultData: {
      photo: '',
      eyebrow: 'EMPLOYER EVENT',
      title: 'Industry Night with Apollo MCE',
      date: 'Thu, Jan 30',
      time: '6:00 PM',
      location: 'Boyd GSRC',
    },
  },
  {
    id: 'recap',
    name: 'Event Recap',
    category: 'Events',
    icon: '',
    component: EventRecapPost,
    pageCount: recapPageCount, // cover slide + one slide per uploaded photo
    fields: [
      { key: 'coverPhoto', label: 'Cover photo', type: 'image' },
      { key: 'eyebrow', label: 'Eyebrow', placeholder: 'EVENT RECAP', type: 'text' },
      { key: 'partner', label: 'Partner / host', placeholder: 'Georgia Power', type: 'text' },
      { key: 'title', label: 'Recap title', placeholder: 'Site Visit Recap', type: 'text' },
      { key: 'date', label: 'Date', placeholder: 'March 13', type: 'text' },
      { key: 'recap', label: 'Recap blurb', placeholder: 'Thank you to everyone who joined us...', type: 'textarea' },
      { key: 'images', label: 'Photos (carousel)', type: 'images' },
    ],
    defaultData: {
      coverPhoto: '',
      eyebrow: 'EVENT RECAP',
      partner: 'Georgia Power',
      title: 'Site Visit Recap',
      date: 'March 13',
      recap: 'Thank you to everyone who joined us — and a huge thanks to our hosts for an unforgettable day.',
      images: [],
    },
  },
  {
    id: 'recap-classic',
    name: 'Event Recap (Classic)',
    category: 'Events',
    icon: '',
    component: EventRecapClassic,
    pageCount: recapClassicPageCount,
    fields: [
      { key: 'coverPhoto', label: 'Cover background photo', type: 'image' },
      { key: 'eyebrow', label: 'Eyebrow', placeholder: 'EVENT RECAP', type: 'text' },
      { key: 'partner', label: 'Partner / host', placeholder: 'Georgia Power', type: 'text' },
      { key: 'title', label: 'Recap title', placeholder: 'Site Visit Recap', type: 'text' },
      { key: 'date', label: 'Date', placeholder: 'March 13', type: 'text' },
      { key: 'recap', label: 'Recap blurb', placeholder: 'Thank you to everyone who joined us...', type: 'textarea' },
      { key: 'images', label: 'Photos (carousel)', type: 'images' },
    ],
    defaultData: {
      coverPhoto: '',
      eyebrow: 'EVENT RECAP',
      partner: 'Georgia Power',
      title: 'Site Visit Recap',
      date: 'March 13',
      recap: 'Thank you to everyone who joined us — and a huge thanks to our hosts for an unforgettable day.',
      images: [],
    },
  },
  {
    id: 'calendar',
    name: 'Semester Calendar',
    category: 'Calendars',
    icon: '',
    component: SemesterCalendarPost,
    defaultSize: 'letter', // letter portrait (8.5 × 11) → exports at 1080 × 1398
    fields: [
      { key: 'title', label: 'Title', placeholder: 'Semester Calendar', type: 'text' },
      { key: 'semester', label: 'Semester', placeholder: 'Fall 2025', type: 'text' },
      { key: 'events', label: 'Events (one per line: Date | Event)', placeholder: 'Jan 30 | Industry Night\nFeb 14 | Apps Due', type: 'textarea' },
    ],
    defaultData: {
      title: 'Semester Calendar',
      semester: 'Fall 2025',
      events: [
        'Jan 30 | Industry Night with Apollo MCE',
        'Feb 14 | E-Board Applications Due',
        'Feb 27 | Resume Workshop',
        'Mar 13 | Georgia Power Site Visit',
        'Mar 27 | PCB Design Workshop',
        'Apr 10 | End-of-Semester Banquet',
      ].join('\n'),
    },
  },
  {
    id: 'spotlight',
    name: 'Member Spotlight',
    category: 'People',
    icon: '',
    component: MemberSpotlightPost,
    fields: [
      { key: 'eyebrow', label: 'Eyebrow', placeholder: 'MEMBER SPOTLIGHT', type: 'text' },
      { key: 'name', label: 'Full name', placeholder: 'Jordan Davis', type: 'text' },
      { key: 'initials', label: 'Initials (2 letters)', placeholder: 'JD', type: 'text' },
      { key: 'year', label: 'Year', placeholder: 'Junior', type: 'text' },
      { key: 'major', label: 'Major', placeholder: 'Electrical & Electronics Engineering', type: 'text' },
      { key: 'quote', label: 'Quote', placeholder: 'What IEEE means to them...', type: 'textarea' },
      { key: 'skills', label: 'Skills (comma-separated)', placeholder: 'PCB Design, Embedded C, Python', type: 'text' },
    ],
    defaultData: {
      eyebrow: 'MEMBER SPOTLIGHT',
      name: 'Anthony Behrend',
      initials: 'AB',
      year: 'Sophomore',
      major: 'Electrical & Electronics Engineering',
      quote: 'IEEE gave me my first real networking opportunity — I landed my summer internship through a contact I made at an employer event.',
      skills: ['Embedded Systems', 'PCB Design', 'Python'],
    },
  },
  {
    id: 'appsopen',
    name: 'Applications Open',
    category: 'Recruitment',
    icon: '',
    component: AppsOpenPost,
    fields: [
      { key: 'photo', label: 'Background photo', type: 'image' },
      { key: 'badge', label: 'Badge', placeholder: 'APPLICATIONS OPEN', type: 'text' },
      { key: 'kicker', label: 'Kicker', placeholder: "WE'RE LOOKING FOR", type: 'text' },
      { key: 'headline', label: 'Headline', placeholder: 'Future E-Board Members.', type: 'text' },
      { key: 'roles', label: 'Open roles (one per line)', placeholder: 'Vice President\nTreasurer\nEvents Chair', type: 'textarea' },
      { key: 'deadline', label: 'Deadline', placeholder: 'Feb 14', type: 'text' },
      { key: 'cta', label: 'Call to action', placeholder: 'APPLY NOW →', type: 'text' },
    ],
    defaultData: {
      photo: '',
      badge: 'APPLICATIONS OPEN',
      kicker: "WE'RE LOOKING FOR",
      headline: 'Future MicroMouse Members.',
      roles: ['Electrical Systems Team', 'Embedded Systems Team'],
      deadline: 'Aug 14',
      cta: 'APPLY NOW →',
    },
  },
  {
    id: 'appsopen-classic',
    name: 'Applications Open (Classic)',
    category: 'Recruitment',
    icon: '',
    component: AppsOpenClassic,
    fields: [
      { key: 'badge', label: 'Badge', placeholder: 'APPLICATIONS OPEN', type: 'text' },
      { key: 'kicker', label: 'Kicker', placeholder: "WE'RE LOOKING FOR", type: 'text' },
      { key: 'headline', label: 'Headline', placeholder: 'Future E-Board Members.', type: 'text' },
      { key: 'roles', label: 'Open roles (one per line)', placeholder: 'Vice President\nTreasurer\nEvents Chair', type: 'textarea' },
      { key: 'deadline', label: 'Deadline', placeholder: 'Feb 14', type: 'text' },
      { key: 'cta', label: 'Call to action', placeholder: 'APPLY NOW →', type: 'text' },
    ],
    defaultData: {
      badge: 'APPLICATIONS OPEN',
      kicker: "WE'RE LOOKING FOR",
      headline: 'Future MicroMouse Members.',
      roles: ['Electrical Systems Team', 'Embedded Systems Team'],
      deadline: 'Aug 14',
      cta: 'APPLY NOW →',
    },
  },
  {
    id: 'eboard',
    name: 'E-Board Reveal',
    category: 'People',
    icon: '',
    component: EBoardPost,
    fields: [
      { key: 'eyebrow', label: 'Eyebrow', placeholder: 'MEET YOUR E-BOARD', type: 'text' },
      { key: 'headline', label: 'Headline', placeholder: "Introducing this year's leadership team.", type: 'text' },
      { key: 'year', label: 'Academic year', placeholder: '2025–26', type: 'text' },
      {
        key: 'members',
        label: 'Members (one per line: Name, Role)',
        placeholder: 'Ava Kim, President\nMarcus R., Vice President\nSofia P., Treasurer',
        type: 'textarea',
      },
    ],
    defaultData: {
      eyebrow: 'MEET YOUR E-BOARD',
      headline: "Introducing this year's leadership team.",
      year: '2026–27',
      members: [
        { initials: 'JC', name: 'Jun Chambers', role: 'President' },
        { initials: 'SJ', name: 'Sidney Johnson', role: 'Vice President' },
        { initials: 'JC', name: 'Joshua Carter', role: 'Outreach Director' },
        { initials: 'JB', name: 'Jacob Bennett', role: 'Engineering Director' },
        { initials: 'DT', name: 'Dillon Thomas', role: 'Treasurer' },
        { initials: 'MM', name: 'Mary Magallanes', role: 'Secretary' },
        { initials: 'ZA', name: 'Zeeshan Ali', role: 'First-Year Advisor' },
        { initials: 'AB', name: 'Anthony Behrend', role: 'First-Year Advisor' },
      ],
    },
  },
  {
    id: 'photooverlay',
    name: 'Photo + Text Overlay',
    category: 'Photos',
    icon: '',
    component: PhotoOverlayPost,
    fields: [
      { key: 'image', label: 'Photo', type: 'image' },
      { key: 'text', label: 'Overlay text', placeholder: 'Add your caption here', type: 'textarea' },
      {
        key: 'position',
        label: 'Text position',
        type: 'select',
        options: [
          { value: 'top-left', label: 'Top left' },
          { value: 'top-center', label: 'Top center' },
          { value: 'top-right', label: 'Top right' },
          { value: 'middle-left', label: 'Middle left' },
          { value: 'middle-center', label: 'Middle center' },
          { value: 'middle-right', label: 'Middle right' },
          { value: 'bottom-left', label: 'Bottom left' },
          { value: 'bottom-center', label: 'Bottom center' },
          { value: 'bottom-right', label: 'Bottom right' },
        ],
      },
    ],
    defaultData: {
      image: '',
      text: 'Add your caption here',
      position: 'bottom-left',
    },
  },
]

export const TEMPLATE_MAP = Object.fromEntries(TEMPLATES.map(t => [t.id, t]))
